apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-web-green
  labels:
    app: demo-web
    color: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-web
      color: green
  template:
    metadata:
      labels:
        app: demo-web
        color: green
    spec:
      containers:
        - name: web
          image: DOCKER_USER/demo-web:{{TAG}}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet: { path: "/", port: 8080 }
            initialDelaySeconds: 2
            periodSeconds: 3
          livenessProbe:
            httpGet: { path: "/", port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 5
